- hosts: all
  become: 'yes'
  gather_facts: false
  tasks:
    - name: Install docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - git-secret
      tags:
        - docker
    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker
    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker
    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker
    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker
    - name: Install docker
      remote_user: ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      #notify: Start docker on boot
      tags:
        - docker
    - name: Add remote "ubuntu" user to "docker" group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker
 #    - name: Install docker-compose
 #      remote_user: ubuntu
 #      get_url: 
 #        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
 #        dest: /usr/local/bin/docker-compose
 #        mode: 'u+x,g+x,a+x'
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install Docker Compose Module for Python
      pip:
        name: docker-compose
