- hosts: all
  become: 'yes'
  gather_facts: false
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/sotcsa/shieldy.git'
        dest: /opt/shieldy
        version: HEAD
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /opt/shieldy 
        state: absent
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /opt/shieldy
        build: yes
      register: output
    - ansible.builtin.debug:
        var: output
